spring:
  application:
    name: KotlinHiberTL
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 16
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    show-aql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase/changelog/changelog.xml
  --data